## OVA (one-vs-all) example

In [9]:
from sklearn.svm import OneClassSVM
import numpy as np

In [3]:
SVM_A = OneClassSVM()
SVM_B = OneClassSVM()

In [61]:
FakeInstaller_A = np.array([1, 1, 1, 1, 2, 3]).reshape(-1,1)
avg_a = np.average([1, 1, 1, 1, 2, 3])
FakeInstaller_B = np.array([1, 1, 2, 2, 3, 3]).reshape(-1,1)
avg_b = np.average([1, 1, 2, 2, 3, 3])

In [57]:
SVM_A.fit(FakeInstaller_A)
SVM_B.fit(FakeInstaller_B)

OneClassSVM(cache_size=200, coef0=0.0, degree=3, gamma='auto', kernel='rbf',
      max_iter=-1, nu=0.5, random_state=None, shrinking=True, tol=0.001,
      verbose=False)

In [64]:
SVM_A.decision_function(avg_a), SVM_A.predict(avg_a)

(array([[0.1020238]]), array([1]))

In [66]:
SVM_B.decision_function(avg_b), SVM_B.predict(avg_b)

(array([[0.00013543]]), array([1]))

In [69]:
SVM_B.decision_function(avg_a), SVM_B.predict(avg_a)

(array([[0.06054066]]), array([1]))

In [68]:
SVM_A.decision_function(1.75), SVM_A.predict(1.75)

(array([[0.05562718]]), array([1]))